# Generated by Django 4.2.17 on 2025-01-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0010_paymentmethod_shippingmethod_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='open', max_length=10),
        ),
    ]
